name: PMD Source Code Analyzer

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      environment:
        description: 'Target environment'
        required: false
        default: 'production'
      testType:
        description: 'Type of tests to run'
        required: true
        default: 'integration'
  push:
    branches : [master]
  # Scheduled for at the end of every day
  schedule:
    - cron: "0 0 * * *"

jobs:
  pmd:
  
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - uses: actions/setup-node@v3
          
      # Setup pmd
      - name: 'Setup PMD'
        uses: sfdx-actions/setup-pmd@v1
      
      # Run PMD Analysis
      - name: 'Run PMD'
        run: |
            pmd -d ./force-app/main/default/ -R category/apex/design.xml -failOnViolation false -f html -shortnames -P linkPrefix="/" -P linePrefix="L" -reportfile ./ReportPMD.html

      # Upload PMD report as an artifact
      - name: 'Upload PMD report'
        uses: actions/upload-artifact@v4
        with:
          name: PMD-Apex-Report
          path: ./ReportPMD.html
          
           
      ###################################
      # Send Email Success
      # https://github.com/marketplace/actions/send-email
      # - name: Send mail Success
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # Required mail server address:
      #     server_address: smtp.gmail.com
      #     # Required mail server port:
      #     server_port: 465
      #     # Optional (recommended): mail server username: Gmail preferred
      #     username: ${{secrets.EMAIL_FROM_USERNAME}}
      #     # Optional (recommended) mail server password: Gmail preferred
      #     password: ${{secrets.EMAIL_FROM_PASSWORD}}
      #     # Required mail subject:
      #     subject: Code Analysis Report - ApexClasses - repo ${{github.repository}} - branch ${{github.ref}}
      #     # Required recipients' addresses:
      #     to: ${{secrets.EMAIL_TO_ADDRESS}}
      #     # Required sender full name (address can be skipped):
      #     from: Test Report
      #     # Optional plain body:
      #     body: Build job of your repository - ${{github.repository}} - branch ${{github.ref}} completed with Success ! Link to job run - ${{ github.server_url }}/${{github.repository}}/actions/runs/${{github.run_id}}
      #     # Optional attachments:
      #     attachments: ./ReportPMD.html
