name:  Test Run on Production Org (scheduled)

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      environment:
        description: 'Target environment'
        required: false
        default: 'production'
      testType:
        description: 'Type of tests to run'
        required: true
        default: 'integration'
  push:
    branches : [master]
  # Scheduled for at the end of every day
  schedule:
    - cron: "0 0 * * *"
    
    
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SFDX_IMPROVED_CODE_COVERAGE: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli -g
          pip install xq
          pip install yq
     
      - name: set proxy server
        run: |          
          export http_proxy=http://${{secrets.ORG_URL}}
          export https_proxy=https://${{secrets.ORG_URL}}
          
      - name: Populate auth file with secret
        shell: bash
        run: 'echo ${{ secrets.AUTHURL_MASTER }} > SFDX_QA'
        
      - name: Auth with the DevHub
        run: 'sfdx force:auth:sfdxurl:store -f SFDX_QA -s -a DevHub -d'      
          
      - name: Run All Test
        run: 'sfdx force:apex:test:run --testlevel RunLocalTests  --resultformat human    --codecoverage >   ./test-result.txt  '

      ###################################
      # Save results
      - name: 'Upload test result report'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apex-code-coverage
          path: ./test-result.txt        
        
      # ###################################
      # # Send Email ERROR Failure
      # # https://github.com/marketplace/actions/send-email
      # - name: Send mail Error Fail
      #   if: ${{ failure() }}
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # Required mail server address:
      #     server_address: smtp.gmail.com
      #     # Required mail server port:
      #     server_port: 465
      #     # Optional (recommended): mail server username:
      #     username: ${{secrets.EMAIL_FROM_USERNAME}}
      #     # Optional (recommended) mail server password:
      #     password: ${{secrets.EMAIL_FROM_PASSWORD}}
      #     # Required mail subject:
      #     subject: Test Report - Error - repo ${{github.repository}} - branch ${{github.ref}}
      #     # Required recipients' addresses:
      #     to: newmoto@allupp.at
      #     # Required sender full name (address can be skipped):
      #     from: Test Report 
      #     # Optional plain body:
      #     body: Build job of your repository - ${{github.repository}} - branch ${{github.ref}} completed with ERROR ! Link to job run - ${{ github.server_url }}/${{github.repository}}/actions/runs/${{github.run_id}}        
      #     # Optional attachments:
      #     attachments: ./test-result.txt
      
      # ###################################
      # # Send Email Success
      # # https://github.com/marketplace/actions/send-email
      # - name: Send mail Success
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     # Required mail server address:
      #     server_address: smtp.gmail.com
      #     # Required mail server port:
      #     server_port: 465
      #     # Optional (recommended): mail server username: Gmail preferred
      #     username: ${{secrets.EMAIL_FROM_USERNAME}}
      #     # Optional (recommended) mail server password: Gmail preferred
      #     password: ${{secrets.EMAIL_FROM_PASSWORD}}
      #     # Required mail subject:
      #     subject: Test Report - Success - repo ${{github.repository}} - branch ${{github.ref}}
      #     # Required recipients' addresses:
      #     to: newmoto@allupp.at
      #     # Required sender full name (address can be skipped):
      #     from: Test Report
      #     # Optional plain body:
      #     body: Build job of your repository - ${{github.repository}} - branch ${{github.ref}} completed with Success ! Link to job run - ${{ github.server_url }}/${{github.repository}}/actions/runs/${{github.run_id}}
      #     # Optional attachments:
      #     attachments: ./test-result.txt
